package dev.zbib.providerservice.enums;

public enum ServiceType {
    PLUMBER,
    ELECTRICIAN,
    REFRIGERATION_TECHNICIAN,
    AIR_CONDITIONING_TECHNICIAN,
    SATELLITE_TECHNICIAN,
    PAINTER,
    ALUMINUM_SPECIALIST,
    GLASS_SPECIALIST,
    CARPENTER,
    TILER,
    GARDENER,
    LOCKSMITH,
    
}
