spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7000
keycloak:
  server-url: http://localhost:8800
  realm: provider-service
  client-id: web-app
  client-secret: lhnLQmgMzfSeVMAGPovEFkXv00Fb3Fz1