spring:
  application:
    name: auth-service
server:
  port: 7000
keycloak:
  server-url: http://localhost:8800
  realm: service-providers
  client-id: web-app
  client-secret: mmr1Vs9HyTISsmevnMHQkbTVlw0FmYr2
