services:
  postgres:
    image: postgres:latest
    container_name: postgres-server
    ports:
      - "5544:5432"
    environment:
      - POSTGRES_USER=guest
      - POSTGRES_PASSWORD=guest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - propal
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin:2.23.2
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - propal

  rabbitMq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - propal


networks:
  propal:
    driver: bridge

volumes:
  rabbitmq_data:
    name: rabbitmq_data
  rabbitmq_logs:
    name: rabbitmq_logs
  db-data:
    name: provider-service-data