services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5544:5432"
    environment:
      - POSTGRES_USER=guest
      - POSTGRES_PASSWORD=guest
      - POSTGRES_DB=auth-service
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - propal
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin:2.23.2
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - propal
    restart: unless-stopped

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - propal
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    command:
      [ "start-dev", "--import-realm" ]
    environment:
      KEYCLOAK_ADMIN: guest
      KEYCLOAK_ADMIN_PASSWORD: guest
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/auth_service
      KC_DB_USERNAME: guest
      KC_DB_PASSWORD: guest
      KC_HEALTH_ENABLED: true
    ports:
      - "8800:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    networks:
      - propal
    restart: unless-stopped

networks:
  propal:
    driver: bridge

volumes:
  rabbitmq_data:
    name: rabbitmq_data
  rabbitmq_logs:
    name: rabbitmq_logs
  db-data:
    name: keycloak_data
