spring:
  application:
    name: provider-service

  datasource:
    url: jdbc:postgresql://localhost:5433/provider_service
    username: guest
    password: guest
    driver-class-name:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true





server:
  port: 8002
