spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5544/user_service
    username: guest
    password: guest
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8001