spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8800/realms/booking-management
server:
  port: 8001
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

keycloak:
  server-url: http://localhost:8800
  realm: booking-management
  client-id: web-app
  client-secret: 7TdiLzPHJZCnOA2Ai14sHpdWctNCHPqV