spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user_service
    username: guest
    password: guest
    driver-class-name:
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/