version: "3.7"
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: user_service
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - propal
    restart: unless-stopped

networks:
  propal:
    driver: bridge

volumes:
  postgres-data:
    driver: local
