name: CI Pipeline

on:
  push:
    branches:
      - '**'  # Trigger on any push to any branch

  pull_request:
    branches:
      - '**'  # Trigger on any PR to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (needed for Spring Boot)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Step 3: Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: Run the tests
      - name: Run Maven tests
        id: test
        run: mvn clean test

      # Step 5: Parse and log test results (using checkmarks and crosses)
      - name: Parse test results
        run: |
          if grep -q 'BUILD SUCCESS' target/surefire-reports/*.txt; then
            echo "✔ All tests passed!" # Success
          else
            echo "❌ Some tests failed!"
          fi
          
          # You can also show detailed logs if you want.
          cat target/surefire-reports/*.txt
