name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Run Unit Tests for Provider Service
        working-directory: provider-service
        run: mvn -B test --file pom.xml

      - name: Run Unit Tests for User Service
        working-directory: user-service
        run: mvn -B test --file pom.xml

      - name: Build Provider Service
        working-directory: provider-service
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build User Service
        working-directory: user-service
        run: |
          mvn clean
          mvn -B package --file pom.xml
