name: Build and Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  test-and-build:
    name: Test and Build Microservices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Unit Tests
        run: mvn clean test -B

      - name: Build All Microservices (using parent POM)
        run: mvn clean package -B

      - name: Upload Build Artifacts (JAR files)
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: |
            user-service/target/*.jar
            api-gateway/target/*.jar
            discovery-server/target/*.jar
            config-server/target/*.jar
            provider-service/target/*.jar

  containerize-and-push:
    name: Containerize and Push Microservices
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Build Artifacts (JAR files)
        uses: actions/download-artifact@v3
        with:
          name: jars

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # Use Docker Buildx for more robust image building and pushing
      - name: Build and Push User Service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: user-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }}

      - name: Build and Push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: .
          file: api-gateway/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{ github.sha }}

      - name: Build and Push Discovery Server
        uses: docker/build-push-action@v4
        with:
          context: .
          file: discovery-server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/discovery-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/discovery-server:${{ github.sha }}

      - name: Build and Push Config Server
        uses: docker/build-push-action@v4
        with:
          context: .
          file: config-server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/config-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/config-server:${{ github.sha }}

      - name: Build and Push Provider Service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: provider-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/provider-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/provider-service:${{ github.sha }}